### ISSUE TITLE
Nothing happened after I enable the add-on.

### ISSUE THREAD

**Issue by possionthefish1** [AnsonSavage/Focal_Lock#2]
![image](https://user-images.githubusercontent.com/92135698/151135535-59d081c7-114e-4925-a8f5-e00ede1b1150.png)

I tried to download it as a zip file, not working. Also tried to download it from google drive (from your youtube channel) still not working.

More info
I'm using Blender version 3.0 but also try to install it in 3.1 which is also not working.
I also updated my python to the latest version (3.10.2) which sadly doesn't help at all lol.

Hope you find the solution soon (only if you have free time that is)
thank you for the free add-on by the way.

**Comment by possionthefish1** [comment]
Edit!!!

I try adding in the new camera and... Yeah, that fixed it I'm such an idiot lol.
Thank you very much again and I'm so sorry!

![image](https://user-images.githubusercontent.com/92135698/151138220-fd6ebc29-005e-4299-bf82-0279a4ff16f8.png)

**Comment by AnsonSavage** [comment]
Hey, this is a very interesting error! So it only worked after you added a
new camera?

**Comment by possionthefish1** [comment]
Greeting Anson

First of all, I would like to apologize again for the confusion. your add-on has no error at all in fact.
The reason it wasn't working at first was because I didn't select the Green symbol (object data properties.)
![image](https://user-images.githubusercontent.com/92135698/151208479-638f7126-6fbc-476c-93a6-8f7106f32a48.png)
But I was selecting the yellow square symbol one so yeah...

I'm very sorry again for the confusion and inconvenience and thank you for the amazing add-on.

**Comment by AnsonSavage** [comment]
Oh, no worries! Okay, I'm glad to hear that it's working!!
