### ISSUE TITLE
install corrupts add-on list Blender 3.0

### ISSUE THREAD

**Issue by ais-lingua** [AnsonSavage/Focal_Lock#3]
Windows 10 21H2
Downloaded the zip file and unzipped it. (Ensured unzipped - examined the .py in VS Code)
Installed in Blender.
Add-on list disappeared.
Renamed ...3.0 to 3.0_bak. Recovered Add ons.

**Comment by AnsonSavage** [comment]
Wow, that's really interesting, I haven't heard of that happening before!
Did you copy the .py file to Blender's addon directory? Or did you install
it from a different directory?

**Comment by ais-lingua** [comment]
I installed it in a different directory, same drive.

**Comment by AnsonSavage** [comment]
That's fascinating! I'm unable to reproduce this error on Windows 10...
Could you Toggle the System Console
<https://docs.blender.org/manual/en/2.79/advanced/command_line/introduction.html#:~:text=Microsoft%20Windows&text=To%20display%20the%20console%20again,Window%20%E2%80%A3%20Toggle%20System%20Console.&text=Blender's%20Console%20Window%20on%20Microsoft,along%20with%20the%20relevant%20messages.>
and
see if there are any errors printed out when you load the addon?

Thanks!
Anson
